/*
 * generated by Xtext 2.13.0
 */
package org.xtext.industryempire.validation

import org.eclipse.xtext.validation.Check
import org.xtext.industryempire.myDsl.ClazzModel
import org.xtext.industryempire.myDsl.MyDslPackage
import org.xtext.industryempire.myDsl.Resources
import org.xtext.industryempire.myDsl.Buildings
import org.xtext.industryempire.myDsl.Cities
import org.xtext.industryempire.myDsl.Vehicles

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MyDslValidator extends AbstractMyDslValidator {
	
	public static val INVALID_NAME = 'invalidName'

	@Check
	def checkGreetingStartsWithCapital(ClazzModel clazzes) {
		if(clazzes.element.filter(Resources).size > 1){
			error("Resources already defined", MyDslPackage.eINSTANCE.clazzModel_Name);
		}
		
		if(clazzes.element.filter(Buildings).size > 1){
			error("Buildings already defined", MyDslPackage.eINSTANCE.clazzModel_Name);
		}
		
		if(clazzes.element.filter(Cities).size > 1){
			error("Cities already defined", MyDslPackage.eINSTANCE.clazzModel_Name);
		}
		
		if(clazzes.element.filter(Vehicles).size > 1){
			error("Vehicles already defined", MyDslPackage.eINSTANCE.clazzModel_Name);
		}
		
	}

	
}
