/**
 * generated by Xtext 2.13.0
 */
package org.xtext.industryempire.ide;

import org.xtext.industryempire.ide.AbstractMyDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
