/*
 * generated by Xtext 2.13.0
 */
package org.xtext.industryempire.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.industryempire.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.industryempire.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Inject
	private MyDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getElementAccess().getAlternatives(), "rule__Element__Alternatives");
					put(grammarAccess.getClazzModelAccess().getGroup(), "rule__ClazzModel__Group__0");
					put(grammarAccess.getCitiesAccess().getGroup(), "rule__Cities__Group__0");
					put(grammarAccess.getCitiesAccess().getGroup_11(), "rule__Cities__Group_11__0");
					put(grammarAccess.getVehiclesAccess().getGroup(), "rule__Vehicles__Group__0");
					put(grammarAccess.getSingleVehicleAccess().getGroup(), "rule__SingleVehicle__Group__0");
					put(grammarAccess.getBuildingsAccess().getGroup(), "rule__Buildings__Group__0");
					put(grammarAccess.getSingleBuildingAccess().getGroup(), "rule__SingleBuilding__Group__0");
					put(grammarAccess.getSingleBuildingAccess().getGroup_2(), "rule__SingleBuilding__Group_2__0");
					put(grammarAccess.getSingleBuildingAccess().getGroup_4(), "rule__SingleBuilding__Group_4__0");
					put(grammarAccess.getResourcesAccess().getGroup(), "rule__Resources__Group__0");
					put(grammarAccess.getSingleResourceAccess().getGroup(), "rule__SingleResource__Group__0");
					put(grammarAccess.getClazzModelAccess().getNameAssignment_1(), "rule__ClazzModel__NameAssignment_1");
					put(grammarAccess.getClazzModelAccess().getElementAssignment_2(), "rule__ClazzModel__ElementAssignment_2");
					put(grammarAccess.getCitiesAccess().getNameAssignment_1(), "rule__Cities__NameAssignment_1");
					put(grammarAccess.getCitiesAccess().getXAssignment_5(), "rule__Cities__XAssignment_5");
					put(grammarAccess.getCitiesAccess().getYAssignment_8(), "rule__Cities__YAssignment_8");
					put(grammarAccess.getCitiesAccess().getFactoryAssignment_10(), "rule__Cities__FactoryAssignment_10");
					put(grammarAccess.getCitiesAccess().getFactoryAssignment_11_1(), "rule__Cities__FactoryAssignment_11_1");
					put(grammarAccess.getVehiclesAccess().getVehiclesAssignment_2(), "rule__Vehicles__VehiclesAssignment_2");
					put(grammarAccess.getSingleVehicleAccess().getNameAssignment_0(), "rule__SingleVehicle__NameAssignment_0");
					put(grammarAccess.getSingleVehicleAccess().getSpeedAssignment_4(), "rule__SingleVehicle__SpeedAssignment_4");
					put(grammarAccess.getSingleVehicleAccess().getLoadAssignment_8(), "rule__SingleVehicle__LoadAssignment_8");
					put(grammarAccess.getSingleVehicleAccess().getTankSizeAssignment_12(), "rule__SingleVehicle__TankSizeAssignment_12");
					put(grammarAccess.getSingleVehicleAccess().getFuelConsumptionAssignment_16(), "rule__SingleVehicle__FuelConsumptionAssignment_16");
					put(grammarAccess.getBuildingsAccess().getFactoriesAssignment_2(), "rule__Buildings__FactoriesAssignment_2");
					put(grammarAccess.getSingleBuildingAccess().getNameAssignment_0(), "rule__SingleBuilding__NameAssignment_0");
					put(grammarAccess.getSingleBuildingAccess().getInputAssignment_2_2(), "rule__SingleBuilding__InputAssignment_2_2");
					put(grammarAccess.getSingleBuildingAccess().getOutputAssignment_4_2(), "rule__SingleBuilding__OutputAssignment_4_2");
					put(grammarAccess.getResourcesAccess().getResourcesAssignment_2(), "rule__Resources__ResourcesAssignment_2");
					put(grammarAccess.getSingleResourceAccess().getNameAssignment_0(), "rule__SingleResource__NameAssignment_0");
					put(grammarAccess.getSingleResourceAccess().getCostAssignment_4(), "rule__SingleResource__CostAssignment_4");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
