/**
 * generated by Xtext 2.13.0
 */
package org.xtext.industryempire.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.industryempire.myDsl.Buildings;
import org.xtext.industryempire.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Buildings</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BuildingsImpl extends ElementImpl implements Buildings
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BuildingsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.BUILDINGS;
  }

} //BuildingsImpl
