/**
 * generated by Xtext 2.13.0
 */
package org.xtext.industryempire.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.industryempire.myDsl.MyDslPackage;
import org.xtext.industryempire.myDsl.SingleVehicle;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Single Vehicle</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.industryempire.myDsl.impl.SingleVehicleImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.industryempire.myDsl.impl.SingleVehicleImpl#getSpeed <em>Speed</em>}</li>
 *   <li>{@link org.xtext.industryempire.myDsl.impl.SingleVehicleImpl#getLoad <em>Load</em>}</li>
 *   <li>{@link org.xtext.industryempire.myDsl.impl.SingleVehicleImpl#getTankSize <em>Tank Size</em>}</li>
 *   <li>{@link org.xtext.industryempire.myDsl.impl.SingleVehicleImpl#getFuelConsumption <em>Fuel Consumption</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SingleVehicleImpl extends MinimalEObjectImpl.Container implements SingleVehicle
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getSpeed() <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpeed()
   * @generated
   * @ordered
   */
  protected static final int SPEED_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSpeed() <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpeed()
   * @generated
   * @ordered
   */
  protected int speed = SPEED_EDEFAULT;

  /**
   * The default value of the '{@link #getLoad() <em>Load</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoad()
   * @generated
   * @ordered
   */
  protected static final int LOAD_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getLoad() <em>Load</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoad()
   * @generated
   * @ordered
   */
  protected int load = LOAD_EDEFAULT;

  /**
   * The default value of the '{@link #getTankSize() <em>Tank Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTankSize()
   * @generated
   * @ordered
   */
  protected static final int TANK_SIZE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTankSize() <em>Tank Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTankSize()
   * @generated
   * @ordered
   */
  protected int tankSize = TANK_SIZE_EDEFAULT;

  /**
   * The default value of the '{@link #getFuelConsumption() <em>Fuel Consumption</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFuelConsumption()
   * @generated
   * @ordered
   */
  protected static final String FUEL_CONSUMPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFuelConsumption() <em>Fuel Consumption</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFuelConsumption()
   * @generated
   * @ordered
   */
  protected String fuelConsumption = FUEL_CONSUMPTION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SingleVehicleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SINGLE_VEHICLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SINGLE_VEHICLE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getSpeed()
  {
    return speed;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSpeed(int newSpeed)
  {
    int oldSpeed = speed;
    speed = newSpeed;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SINGLE_VEHICLE__SPEED, oldSpeed, speed));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getLoad()
  {
    return load;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLoad(int newLoad)
  {
    int oldLoad = load;
    load = newLoad;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SINGLE_VEHICLE__LOAD, oldLoad, load));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getTankSize()
  {
    return tankSize;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTankSize(int newTankSize)
  {
    int oldTankSize = tankSize;
    tankSize = newTankSize;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SINGLE_VEHICLE__TANK_SIZE, oldTankSize, tankSize));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getFuelConsumption()
  {
    return fuelConsumption;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFuelConsumption(String newFuelConsumption)
  {
    String oldFuelConsumption = fuelConsumption;
    fuelConsumption = newFuelConsumption;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SINGLE_VEHICLE__FUEL_CONSUMPTION, oldFuelConsumption, fuelConsumption));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.SINGLE_VEHICLE__NAME:
        return getName();
      case MyDslPackage.SINGLE_VEHICLE__SPEED:
        return getSpeed();
      case MyDslPackage.SINGLE_VEHICLE__LOAD:
        return getLoad();
      case MyDslPackage.SINGLE_VEHICLE__TANK_SIZE:
        return getTankSize();
      case MyDslPackage.SINGLE_VEHICLE__FUEL_CONSUMPTION:
        return getFuelConsumption();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.SINGLE_VEHICLE__NAME:
        setName((String)newValue);
        return;
      case MyDslPackage.SINGLE_VEHICLE__SPEED:
        setSpeed((Integer)newValue);
        return;
      case MyDslPackage.SINGLE_VEHICLE__LOAD:
        setLoad((Integer)newValue);
        return;
      case MyDslPackage.SINGLE_VEHICLE__TANK_SIZE:
        setTankSize((Integer)newValue);
        return;
      case MyDslPackage.SINGLE_VEHICLE__FUEL_CONSUMPTION:
        setFuelConsumption((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SINGLE_VEHICLE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslPackage.SINGLE_VEHICLE__SPEED:
        setSpeed(SPEED_EDEFAULT);
        return;
      case MyDslPackage.SINGLE_VEHICLE__LOAD:
        setLoad(LOAD_EDEFAULT);
        return;
      case MyDslPackage.SINGLE_VEHICLE__TANK_SIZE:
        setTankSize(TANK_SIZE_EDEFAULT);
        return;
      case MyDslPackage.SINGLE_VEHICLE__FUEL_CONSUMPTION:
        setFuelConsumption(FUEL_CONSUMPTION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SINGLE_VEHICLE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslPackage.SINGLE_VEHICLE__SPEED:
        return speed != SPEED_EDEFAULT;
      case MyDslPackage.SINGLE_VEHICLE__LOAD:
        return load != LOAD_EDEFAULT;
      case MyDslPackage.SINGLE_VEHICLE__TANK_SIZE:
        return tankSize != TANK_SIZE_EDEFAULT;
      case MyDslPackage.SINGLE_VEHICLE__FUEL_CONSUMPTION:
        return FUEL_CONSUMPTION_EDEFAULT == null ? fuelConsumption != null : !FUEL_CONSUMPTION_EDEFAULT.equals(fuelConsumption);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", speed: ");
    result.append(speed);
    result.append(", load: ");
    result.append(load);
    result.append(", tankSize: ");
    result.append(tankSize);
    result.append(", fuelConsumption: ");
    result.append(fuelConsumption);
    result.append(')');
    return result.toString();
  }

} //SingleVehicleImpl
