/**
 * generated by Xtext 2.13.0
 */
package org.xtext.industryempire.validation;

import org.eclipse.xtext.validation.Check;
import org.xtext.industryempire.myDsl.ClazzModel;
import org.xtext.industryempire.myDsl.MyDslPackage;
import org.xtext.industryempire.validation.AbstractMyDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MyDslValidator extends AbstractMyDslValidator {
  public final static String INVALID_NAME = "invalidName";
  
  @Check
  public void checkGreetingStartsWithCapital(final ClazzModel clazzes) {
    boolean _equals = clazzes.getElement().get(0).equals("Resources");
    boolean _not = (!_equals);
    if (_not) {
      this.error("Resource must be 1", MyDslPackage.eINSTANCE.eContainingFeature());
    }
  }
}
