/*
 * generated by Xtext 2.13.0
 */
package org.xtext.industryempire.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.industryempire.ui.internal.IndustryempireActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(IndustryempireActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		IndustryempireActivator activator = IndustryempireActivator.getInstance();
		return activator != null ? activator.getInjector(IndustryempireActivator.ORG_XTEXT_INDUSTRYEMPIRE_MYDSL) : null;
	}

}
