/**
 * generated by Xtext 2.13.0
 */
package org.xtext.industryempire.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Buildings</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.industryempire.myDsl.MyDslPackage#getBuildings()
 * @model
 * @generated
 */
public interface Buildings extends Element
{
} // Buildings
