/**
 * generated by Xtext 2.13.0
 */
package org.xtext.industryempire.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cities</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.industryempire.myDsl.Cities#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.industryempire.myDsl.Cities#getX <em>X</em>}</li>
 *   <li>{@link org.xtext.industryempire.myDsl.Cities#getY <em>Y</em>}</li>
 *   <li>{@link org.xtext.industryempire.myDsl.Cities#getFactory <em>Factory</em>}</li>
 * </ul>
 *
 * @see org.xtext.industryempire.myDsl.MyDslPackage#getCities()
 * @model
 * @generated
 */
public interface Cities extends Element
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.industryempire.myDsl.MyDslPackage#getCities_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.industryempire.myDsl.Cities#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>X</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(int)
   * @see org.xtext.industryempire.myDsl.MyDslPackage#getCities_X()
   * @model
   * @generated
   */
  int getX();

  /**
   * Sets the value of the '{@link org.xtext.industryempire.myDsl.Cities#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(int value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Y</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(int)
   * @see org.xtext.industryempire.myDsl.MyDslPackage#getCities_Y()
   * @model
   * @generated
   */
  int getY();

  /**
   * Sets the value of the '{@link org.xtext.industryempire.myDsl.Cities#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(int value);

  /**
   * Returns the value of the '<em><b>Factory</b></em>' reference list.
   * The list contents are of type {@link org.xtext.industryempire.myDsl.SingleFactory}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Factory</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Factory</em>' reference list.
   * @see org.xtext.industryempire.myDsl.MyDslPackage#getCities_Factory()
   * @model
   * @generated
   */
  EList<SingleFactory> getFactory();

} // Cities
