/**
 * generated by Xtext 2.13.0
 */
package org.xtext.industryempire.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clazz Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.industryempire.myDsl.ClazzModel#getElement <em>Element</em>}</li>
 * </ul>
 *
 * @see org.xtext.industryempire.myDsl.MyDslPackage#getClazzModel()
 * @model
 * @generated
 */
public interface ClazzModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Element</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.industryempire.myDsl.Element}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Element</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' containment reference list.
   * @see org.xtext.industryempire.myDsl.MyDslPackage#getClazzModel_Element()
   * @model containment="true"
   * @generated
   */
  EList<Element> getElement();

} // ClazzModel
