/**
 * generated by Xtext 2.13.0
 */
package org.xtext.industryempire.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.industryempire.myDsl.MyDslPackage#getElement()
 * @model
 * @generated
 */
public interface Element extends EObject
{
} // Element
