/**
 * generated by Xtext 2.13.0
 */
package org.xtext.industryempire.myDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.industryempire.myDsl.MyDslPackage
 * @generated
 */
public interface MyDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslFactory eINSTANCE = org.xtext.industryempire.myDsl.impl.MyDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Clazz Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Clazz Model</em>'.
   * @generated
   */
  ClazzModel createClazzModel();

  /**
   * Returns a new object of class '<em>Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element</em>'.
   * @generated
   */
  Element createElement();

  /**
   * Returns a new object of class '<em>Cities</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cities</em>'.
   * @generated
   */
  Cities createCities();

  /**
   * Returns a new object of class '<em>Vehicles</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Vehicles</em>'.
   * @generated
   */
  Vehicles createVehicles();

  /**
   * Returns a new object of class '<em>Single Vehicle</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Single Vehicle</em>'.
   * @generated
   */
  SingleVehicle createSingleVehicle();

  /**
   * Returns a new object of class '<em>Buildings</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Buildings</em>'.
   * @generated
   */
  Buildings createBuildings();

  /**
   * Returns a new object of class '<em>Single Building</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Single Building</em>'.
   * @generated
   */
  SingleBuilding createSingleBuilding();

  /**
   * Returns a new object of class '<em>Resources</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Resources</em>'.
   * @generated
   */
  Resources createResources();

  /**
   * Returns a new object of class '<em>Single Resource</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Single Resource</em>'.
   * @generated
   */
  SingleResource createSingleResource();

  /**
   * Returns a new object of class '<em>Factories</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Factories</em>'.
   * @generated
   */
  Factories createFactories();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MyDslPackage getMyDslPackage();

} //MyDslFactory
