/**
 * generated by Xtext 2.13.0
 */
package org.xtext.industryempire.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.industryempire.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/industryempire/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.industryempire.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.industryempire.myDsl.impl.ClazzModelImpl <em>Clazz Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.industryempire.myDsl.impl.ClazzModelImpl
   * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getClazzModel()
   * @generated
   */
  int CLAZZ_MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAZZ_MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAZZ_MODEL__ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Clazz Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAZZ_MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.industryempire.myDsl.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.industryempire.myDsl.impl.ElementImpl
   * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.industryempire.myDsl.impl.CitiesImpl <em>Cities</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.industryempire.myDsl.impl.CitiesImpl
   * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getCities()
   * @generated
   */
  int CITIES = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CITIES__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CITIES__X = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CITIES__Y = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Factory</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CITIES__FACTORY = ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Cities</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CITIES_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.industryempire.myDsl.impl.VehiclesImpl <em>Vehicles</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.industryempire.myDsl.impl.VehiclesImpl
   * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getVehicles()
   * @generated
   */
  int VEHICLES = 3;

  /**
   * The feature id for the '<em><b>Vehicles</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VEHICLES__VEHICLES = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Vehicles</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VEHICLES_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.industryempire.myDsl.impl.SingleVehicleImpl <em>Single Vehicle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.industryempire.myDsl.impl.SingleVehicleImpl
   * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getSingleVehicle()
   * @generated
   */
  int SINGLE_VEHICLE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_VEHICLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_VEHICLE__SPEED = 1;

  /**
   * The feature id for the '<em><b>Load</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_VEHICLE__LOAD = 2;

  /**
   * The feature id for the '<em><b>Tank Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_VEHICLE__TANK_SIZE = 3;

  /**
   * The feature id for the '<em><b>Fuel Consumption</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_VEHICLE__FUEL_CONSUMPTION = 4;

  /**
   * The number of structural features of the '<em>Single Vehicle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_VEHICLE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.industryempire.myDsl.impl.BuildingsImpl <em>Buildings</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.industryempire.myDsl.impl.BuildingsImpl
   * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getBuildings()
   * @generated
   */
  int BUILDINGS = 5;

  /**
   * The number of structural features of the '<em>Buildings</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUILDINGS_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.industryempire.myDsl.impl.SingleBuildingImpl <em>Single Building</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.industryempire.myDsl.impl.SingleBuildingImpl
   * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getSingleBuilding()
   * @generated
   */
  int SINGLE_BUILDING = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_BUILDING__NAME = 0;

  /**
   * The feature id for the '<em><b>Input</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_BUILDING__INPUT = 1;

  /**
   * The feature id for the '<em><b>Output</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_BUILDING__OUTPUT = 2;

  /**
   * The number of structural features of the '<em>Single Building</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_BUILDING_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.industryempire.myDsl.impl.ResourcesImpl <em>Resources</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.industryempire.myDsl.impl.ResourcesImpl
   * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getResources()
   * @generated
   */
  int RESOURCES = 7;

  /**
   * The feature id for the '<em><b>Resources</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCES__RESOURCES = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Resources</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCES_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.industryempire.myDsl.impl.SingleResourceImpl <em>Single Resource</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.industryempire.myDsl.impl.SingleResourceImpl
   * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getSingleResource()
   * @generated
   */
  int SINGLE_RESOURCE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_RESOURCE__NAME = 0;

  /**
   * The feature id for the '<em><b>Cost</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_RESOURCE__COST = 1;

  /**
   * The number of structural features of the '<em>Single Resource</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_RESOURCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.industryempire.myDsl.impl.FactoriesImpl <em>Factories</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.industryempire.myDsl.impl.FactoriesImpl
   * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getFactories()
   * @generated
   */
  int FACTORIES = 9;

  /**
   * The feature id for the '<em><b>Factories</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTORIES__FACTORIES = BUILDINGS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Factories</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTORIES_FEATURE_COUNT = BUILDINGS_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.industryempire.myDsl.ClazzModel <em>Clazz Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Clazz Model</em>'.
   * @see org.xtext.industryempire.myDsl.ClazzModel
   * @generated
   */
  EClass getClazzModel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.industryempire.myDsl.ClazzModel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.industryempire.myDsl.ClazzModel#getName()
   * @see #getClazzModel()
   * @generated
   */
  EAttribute getClazzModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.industryempire.myDsl.ClazzModel#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element</em>'.
   * @see org.xtext.industryempire.myDsl.ClazzModel#getElement()
   * @see #getClazzModel()
   * @generated
   */
  EReference getClazzModel_Element();

  /**
   * Returns the meta object for class '{@link org.xtext.industryempire.myDsl.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.industryempire.myDsl.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for class '{@link org.xtext.industryempire.myDsl.Cities <em>Cities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cities</em>'.
   * @see org.xtext.industryempire.myDsl.Cities
   * @generated
   */
  EClass getCities();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.industryempire.myDsl.Cities#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Name</em>'.
   * @see org.xtext.industryempire.myDsl.Cities#getName()
   * @see #getCities()
   * @generated
   */
  EAttribute getCities_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.industryempire.myDsl.Cities#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.xtext.industryempire.myDsl.Cities#getX()
   * @see #getCities()
   * @generated
   */
  EAttribute getCities_X();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.industryempire.myDsl.Cities#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see org.xtext.industryempire.myDsl.Cities#getY()
   * @see #getCities()
   * @generated
   */
  EAttribute getCities_Y();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.industryempire.myDsl.Cities#getFactory <em>Factory</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Factory</em>'.
   * @see org.xtext.industryempire.myDsl.Cities#getFactory()
   * @see #getCities()
   * @generated
   */
  EReference getCities_Factory();

  /**
   * Returns the meta object for class '{@link org.xtext.industryempire.myDsl.Vehicles <em>Vehicles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vehicles</em>'.
   * @see org.xtext.industryempire.myDsl.Vehicles
   * @generated
   */
  EClass getVehicles();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.industryempire.myDsl.Vehicles#getVehicles <em>Vehicles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vehicles</em>'.
   * @see org.xtext.industryempire.myDsl.Vehicles#getVehicles()
   * @see #getVehicles()
   * @generated
   */
  EReference getVehicles_Vehicles();

  /**
   * Returns the meta object for class '{@link org.xtext.industryempire.myDsl.SingleVehicle <em>Single Vehicle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Single Vehicle</em>'.
   * @see org.xtext.industryempire.myDsl.SingleVehicle
   * @generated
   */
  EClass getSingleVehicle();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.industryempire.myDsl.SingleVehicle#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.industryempire.myDsl.SingleVehicle#getName()
   * @see #getSingleVehicle()
   * @generated
   */
  EAttribute getSingleVehicle_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.industryempire.myDsl.SingleVehicle#getSpeed <em>Speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Speed</em>'.
   * @see org.xtext.industryempire.myDsl.SingleVehicle#getSpeed()
   * @see #getSingleVehicle()
   * @generated
   */
  EAttribute getSingleVehicle_Speed();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.industryempire.myDsl.SingleVehicle#getLoad <em>Load</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Load</em>'.
   * @see org.xtext.industryempire.myDsl.SingleVehicle#getLoad()
   * @see #getSingleVehicle()
   * @generated
   */
  EAttribute getSingleVehicle_Load();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.industryempire.myDsl.SingleVehicle#getTankSize <em>Tank Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tank Size</em>'.
   * @see org.xtext.industryempire.myDsl.SingleVehicle#getTankSize()
   * @see #getSingleVehicle()
   * @generated
   */
  EAttribute getSingleVehicle_TankSize();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.industryempire.myDsl.SingleVehicle#getFuelConsumption <em>Fuel Consumption</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fuel Consumption</em>'.
   * @see org.xtext.industryempire.myDsl.SingleVehicle#getFuelConsumption()
   * @see #getSingleVehicle()
   * @generated
   */
  EAttribute getSingleVehicle_FuelConsumption();

  /**
   * Returns the meta object for class '{@link org.xtext.industryempire.myDsl.Buildings <em>Buildings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Buildings</em>'.
   * @see org.xtext.industryempire.myDsl.Buildings
   * @generated
   */
  EClass getBuildings();

  /**
   * Returns the meta object for class '{@link org.xtext.industryempire.myDsl.SingleBuilding <em>Single Building</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Single Building</em>'.
   * @see org.xtext.industryempire.myDsl.SingleBuilding
   * @generated
   */
  EClass getSingleBuilding();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.industryempire.myDsl.SingleBuilding#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.industryempire.myDsl.SingleBuilding#getName()
   * @see #getSingleBuilding()
   * @generated
   */
  EAttribute getSingleBuilding_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.industryempire.myDsl.SingleBuilding#getInput <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Input</em>'.
   * @see org.xtext.industryempire.myDsl.SingleBuilding#getInput()
   * @see #getSingleBuilding()
   * @generated
   */
  EReference getSingleBuilding_Input();

  /**
   * Returns the meta object for the reference '{@link org.xtext.industryempire.myDsl.SingleBuilding#getOutput <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Output</em>'.
   * @see org.xtext.industryempire.myDsl.SingleBuilding#getOutput()
   * @see #getSingleBuilding()
   * @generated
   */
  EReference getSingleBuilding_Output();

  /**
   * Returns the meta object for class '{@link org.xtext.industryempire.myDsl.Resources <em>Resources</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Resources</em>'.
   * @see org.xtext.industryempire.myDsl.Resources
   * @generated
   */
  EClass getResources();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.industryempire.myDsl.Resources#getResources <em>Resources</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Resources</em>'.
   * @see org.xtext.industryempire.myDsl.Resources#getResources()
   * @see #getResources()
   * @generated
   */
  EReference getResources_Resources();

  /**
   * Returns the meta object for class '{@link org.xtext.industryempire.myDsl.SingleResource <em>Single Resource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Single Resource</em>'.
   * @see org.xtext.industryempire.myDsl.SingleResource
   * @generated
   */
  EClass getSingleResource();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.industryempire.myDsl.SingleResource#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.industryempire.myDsl.SingleResource#getName()
   * @see #getSingleResource()
   * @generated
   */
  EAttribute getSingleResource_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.industryempire.myDsl.SingleResource#getCost <em>Cost</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cost</em>'.
   * @see org.xtext.industryempire.myDsl.SingleResource#getCost()
   * @see #getSingleResource()
   * @generated
   */
  EAttribute getSingleResource_Cost();

  /**
   * Returns the meta object for class '{@link org.xtext.industryempire.myDsl.Factories <em>Factories</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Factories</em>'.
   * @see org.xtext.industryempire.myDsl.Factories
   * @generated
   */
  EClass getFactories();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.industryempire.myDsl.Factories#getFactories <em>Factories</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Factories</em>'.
   * @see org.xtext.industryempire.myDsl.Factories#getFactories()
   * @see #getFactories()
   * @generated
   */
  EReference getFactories_Factories();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.industryempire.myDsl.impl.ClazzModelImpl <em>Clazz Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.industryempire.myDsl.impl.ClazzModelImpl
     * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getClazzModel()
     * @generated
     */
    EClass CLAZZ_MODEL = eINSTANCE.getClazzModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLAZZ_MODEL__NAME = eINSTANCE.getClazzModel_Name();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLAZZ_MODEL__ELEMENT = eINSTANCE.getClazzModel_Element();

    /**
     * The meta object literal for the '{@link org.xtext.industryempire.myDsl.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.industryempire.myDsl.impl.ElementImpl
     * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '{@link org.xtext.industryempire.myDsl.impl.CitiesImpl <em>Cities</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.industryempire.myDsl.impl.CitiesImpl
     * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getCities()
     * @generated
     */
    EClass CITIES = eINSTANCE.getCities();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CITIES__NAME = eINSTANCE.getCities_Name();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CITIES__X = eINSTANCE.getCities_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CITIES__Y = eINSTANCE.getCities_Y();

    /**
     * The meta object literal for the '<em><b>Factory</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CITIES__FACTORY = eINSTANCE.getCities_Factory();

    /**
     * The meta object literal for the '{@link org.xtext.industryempire.myDsl.impl.VehiclesImpl <em>Vehicles</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.industryempire.myDsl.impl.VehiclesImpl
     * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getVehicles()
     * @generated
     */
    EClass VEHICLES = eINSTANCE.getVehicles();

    /**
     * The meta object literal for the '<em><b>Vehicles</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VEHICLES__VEHICLES = eINSTANCE.getVehicles_Vehicles();

    /**
     * The meta object literal for the '{@link org.xtext.industryempire.myDsl.impl.SingleVehicleImpl <em>Single Vehicle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.industryempire.myDsl.impl.SingleVehicleImpl
     * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getSingleVehicle()
     * @generated
     */
    EClass SINGLE_VEHICLE = eINSTANCE.getSingleVehicle();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_VEHICLE__NAME = eINSTANCE.getSingleVehicle_Name();

    /**
     * The meta object literal for the '<em><b>Speed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_VEHICLE__SPEED = eINSTANCE.getSingleVehicle_Speed();

    /**
     * The meta object literal for the '<em><b>Load</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_VEHICLE__LOAD = eINSTANCE.getSingleVehicle_Load();

    /**
     * The meta object literal for the '<em><b>Tank Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_VEHICLE__TANK_SIZE = eINSTANCE.getSingleVehicle_TankSize();

    /**
     * The meta object literal for the '<em><b>Fuel Consumption</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_VEHICLE__FUEL_CONSUMPTION = eINSTANCE.getSingleVehicle_FuelConsumption();

    /**
     * The meta object literal for the '{@link org.xtext.industryempire.myDsl.impl.BuildingsImpl <em>Buildings</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.industryempire.myDsl.impl.BuildingsImpl
     * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getBuildings()
     * @generated
     */
    EClass BUILDINGS = eINSTANCE.getBuildings();

    /**
     * The meta object literal for the '{@link org.xtext.industryempire.myDsl.impl.SingleBuildingImpl <em>Single Building</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.industryempire.myDsl.impl.SingleBuildingImpl
     * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getSingleBuilding()
     * @generated
     */
    EClass SINGLE_BUILDING = eINSTANCE.getSingleBuilding();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_BUILDING__NAME = eINSTANCE.getSingleBuilding_Name();

    /**
     * The meta object literal for the '<em><b>Input</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SINGLE_BUILDING__INPUT = eINSTANCE.getSingleBuilding_Input();

    /**
     * The meta object literal for the '<em><b>Output</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SINGLE_BUILDING__OUTPUT = eINSTANCE.getSingleBuilding_Output();

    /**
     * The meta object literal for the '{@link org.xtext.industryempire.myDsl.impl.ResourcesImpl <em>Resources</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.industryempire.myDsl.impl.ResourcesImpl
     * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getResources()
     * @generated
     */
    EClass RESOURCES = eINSTANCE.getResources();

    /**
     * The meta object literal for the '<em><b>Resources</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESOURCES__RESOURCES = eINSTANCE.getResources_Resources();

    /**
     * The meta object literal for the '{@link org.xtext.industryempire.myDsl.impl.SingleResourceImpl <em>Single Resource</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.industryempire.myDsl.impl.SingleResourceImpl
     * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getSingleResource()
     * @generated
     */
    EClass SINGLE_RESOURCE = eINSTANCE.getSingleResource();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_RESOURCE__NAME = eINSTANCE.getSingleResource_Name();

    /**
     * The meta object literal for the '<em><b>Cost</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_RESOURCE__COST = eINSTANCE.getSingleResource_Cost();

    /**
     * The meta object literal for the '{@link org.xtext.industryempire.myDsl.impl.FactoriesImpl <em>Factories</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.industryempire.myDsl.impl.FactoriesImpl
     * @see org.xtext.industryempire.myDsl.impl.MyDslPackageImpl#getFactories()
     * @generated
     */
    EClass FACTORIES = eINSTANCE.getFactories();

    /**
     * The meta object literal for the '<em><b>Factories</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACTORIES__FACTORIES = eINSTANCE.getFactories_Factories();

  }

} //MyDslPackage
