/**
 * generated by Xtext 2.13.0
 */
package org.xtext.industryempire.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Vehicle</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.industryempire.myDsl.SingleVehicle#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.industryempire.myDsl.SingleVehicle#getSpeed <em>Speed</em>}</li>
 *   <li>{@link org.xtext.industryempire.myDsl.SingleVehicle#getLoad <em>Load</em>}</li>
 *   <li>{@link org.xtext.industryempire.myDsl.SingleVehicle#getTankSize <em>Tank Size</em>}</li>
 *   <li>{@link org.xtext.industryempire.myDsl.SingleVehicle#getFuelConsumption <em>Fuel Consumption</em>}</li>
 * </ul>
 *
 * @see org.xtext.industryempire.myDsl.MyDslPackage#getSingleVehicle()
 * @model
 * @generated
 */
public interface SingleVehicle extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.industryempire.myDsl.MyDslPackage#getSingleVehicle_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.industryempire.myDsl.SingleVehicle#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Speed</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Speed</em>' attribute.
   * @see #setSpeed(int)
   * @see org.xtext.industryempire.myDsl.MyDslPackage#getSingleVehicle_Speed()
   * @model
   * @generated
   */
  int getSpeed();

  /**
   * Sets the value of the '{@link org.xtext.industryempire.myDsl.SingleVehicle#getSpeed <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Speed</em>' attribute.
   * @see #getSpeed()
   * @generated
   */
  void setSpeed(int value);

  /**
   * Returns the value of the '<em><b>Load</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Load</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Load</em>' attribute.
   * @see #setLoad(int)
   * @see org.xtext.industryempire.myDsl.MyDslPackage#getSingleVehicle_Load()
   * @model
   * @generated
   */
  int getLoad();

  /**
   * Sets the value of the '{@link org.xtext.industryempire.myDsl.SingleVehicle#getLoad <em>Load</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Load</em>' attribute.
   * @see #getLoad()
   * @generated
   */
  void setLoad(int value);

  /**
   * Returns the value of the '<em><b>Tank Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tank Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tank Size</em>' attribute.
   * @see #setTankSize(int)
   * @see org.xtext.industryempire.myDsl.MyDslPackage#getSingleVehicle_TankSize()
   * @model
   * @generated
   */
  int getTankSize();

  /**
   * Sets the value of the '{@link org.xtext.industryempire.myDsl.SingleVehicle#getTankSize <em>Tank Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tank Size</em>' attribute.
   * @see #getTankSize()
   * @generated
   */
  void setTankSize(int value);

  /**
   * Returns the value of the '<em><b>Fuel Consumption</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fuel Consumption</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fuel Consumption</em>' attribute.
   * @see #setFuelConsumption(String)
   * @see org.xtext.industryempire.myDsl.MyDslPackage#getSingleVehicle_FuelConsumption()
   * @model
   * @generated
   */
  String getFuelConsumption();

  /**
   * Sets the value of the '{@link org.xtext.industryempire.myDsl.SingleVehicle#getFuelConsumption <em>Fuel Consumption</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fuel Consumption</em>' attribute.
   * @see #getFuelConsumption()
   * @generated
   */
  void setFuelConsumption(String value);

} // SingleVehicle
