/**
 * generated by Xtext 2.13.0
 */
package org.xtext.industryempire.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vehicles</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.industryempire.myDsl.Vehicles#getVehicles <em>Vehicles</em>}</li>
 * </ul>
 *
 * @see org.xtext.industryempire.myDsl.MyDslPackage#getVehicles()
 * @model
 * @generated
 */
public interface Vehicles extends Element
{
  /**
   * Returns the value of the '<em><b>Vehicles</b></em>' reference list.
   * The list contents are of type {@link org.xtext.industryempire.myDsl.SingleVehicle}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Vehicles</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vehicles</em>' reference list.
   * @see org.xtext.industryempire.myDsl.MyDslPackage#getVehicles_Vehicles()
   * @model
   * @generated
   */
  EList<SingleVehicle> getVehicles();

} // Vehicles
